### ISSUE TITLE
undefined method in Version 1.0.16

### ISSUE THREAD

**Issue by QuBiT** [cucumber-attic/gherkin2#51]
after upgrading to 1.0.16 I get this error:

<pre><code>
undefined method `feature_keywords' for #<Gherkin::I18n:0x4f69de8>
.../gherkin-1.0.16-x86-mingw32/lib/gherkin/i18n.rb:39:in `__send__'
.../gherkin-1.0.16-x86-mingw32/lib/gherkin/i18n.rb:39:in `keyword_regexp'
.../gherkin-1.0.16-x86-mingw32/lib/gherkin/i18n.rb:38:in `map'
.../gherkin-1.0.16-x86-mingw32/lib/gherkin/i18n.rb:38:in `keyword_regexp'
.../gherkin-1.0.16-x86-mingw32/lib/gherkin/i18n.rb:37:in `map'
.../gherkin-1.0.16-x86-mingw32/lib/gherkin/i18n.rb:37:in `keyword_regexp'
...:in `gherkin_keywords'
</code></pre>
